#index:
#    path: /
#    controller: App\Controller\DefaultController::index
gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
api_login_check:
  path: /api/login_check
api_country_create:
  path: /api/country
  controller: App\Controller\CountryController:new
  methods: POST
api_website_create:
  path: /api/website
  controller: App\Controller\WebsiteController:new
  methods: POST